import React, { Component } from 'react'

export default class Tos extends Component {
  render() {
    return (
      <div>
        <p>
        Welcome to Compoundex.io, a website of Anonymous, Inc. ("Compoundex", “we”, “our”, or “us”). This page explains the terms by which you may use our website (the “Site”). By accessing or using the Site, you signify that you have read, understood, and agree to be bound by this Terms of Service Agreement (“Agreement”) and to the collection and use of your information as set forth in the Compoundex Privacy Policy [link], whether or not you are a registered user of our Site. Compoundex reserves the right to make unilateral modifications to these terms and will provide notice of these changes as described below. This Agreement applies to all visitors, users, and others who access the Site (“Users”).
            Please read this Agreement carefully to ensure that you understand each provision. This agreement contains a mandatory individual arbitration and class action/jury trial waiver provision that requires the use of arbitration on an individual basis to resolve disputes, rather than jury trials or class actions.

            Compoundex Site.
            As part of the Site, Compoundex provides access to a decentralized money market protocol (“Protocol”) that allows suppliers or borrowers of blockchain assets (“Assets”) to exchange their assets on the applicable blockchain through Compoundex-provided smart contracts (“Smart Contracts”).
            Use of Our Site.
            A. Eligibility
            This is a contract between you and Compound. You must read and agree to these terms before using the Site. If you do not agree, you may not use the Site. You may use the Site only if you can form a binding contract with Compound, and only in compliance with this Agreement and all applicable local, state, national, and international laws, rules and regulations. Any use or access to the Site by anyone under eighteen (18) years of age is strictly prohibited and in violation of this Agreement. The Site is not available to any Users previously removed from the Site by Compoundex.

            B. Access and Use of the Site and Smart Contracts
            Subject to the terms and conditions of this Agreement, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Site as permitted by the features of the Site. Compoundex reserves all rights not expressly granted herein in the Site and the CompoundexContent (as defined below). The license grant to you in this Section 2(B) includes, without limitation, the right to use our Protocol and Smart Contracts, which are made available to Users at https://Compoundex.io/developers. Compoundex may terminate this license, in whole or in part, at any time for any reason or no reason.

            C. Site Rules
            You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Site in any medium, including without limitation by any automated or non-automated “scraping”; (ii) using any automated system, including without limitation “robots,” “spiders,” “offline readers,” etc., to access the Site in a manner that sends more request messages to the Compoundex servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that Compoundex grants the operators of public search engines revocable permission to use spiders to copy publically available materials from Compound.com for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials); (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Site; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Site; (vii) collecting or harvesting any personally identifiable information, including account names, from the Site; (viii) using the Site for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Site; (xi) accessing any content on the Site through any technology or means other than those provided or authorized by the Site; or (xii) bypassing the measures we may use to prevent or restrict access to the Site, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Site or the content therein.

            We may, without prior notice, change the Site; stop providing the Site or features of the Site, to you or to Users generally; or create usage limits for the Site. We may permanently or temporarily terminate or suspend your access to the Site without notice and liability for any reason, including if in our sole determination you violate any provision of this Agreement, or for no reason. Upon termination for any reason or no reason, you continue to be bound by this Agreement.

            You are solely responsible for your interactions with other Compoundex Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users. Compoundex shall have no liability for your interactions with other Users, or for any User’s action or inaction.

            Our Proprietary Rights.
            The Site, the Protocol, the Smart Contracts and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the “Compoundex Content”), and all Intellectual Property Rights related thereto, are the exclusive property of Compoundexand its licensors. Except as explicitly provided herein, nothing in this Agreement shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any CompoundexContent. Use of the CompoundexContent for any purpose not expressly permitted by this Agreement is strictly prohibited.

            You may choose to or we may invite you to submit comments or ideas about the Site, including without limitation about how to improve the Site or our products (“Ideas”). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place Compoundex under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, Compoundex does not waive any rights to use similar or related ideas previously known to Compoundex, or developed by its employees, or obtained from sources other than you.

            No Professional Advice.
            If the Site provides professional information (for example, medical, legal, or financial), such information is for informational purposes only and should not be construed as professional advice. No action should be taken based upon any information contained in the Site. You should seek independent professional advice from a person who is licensed and/or qualified in the applicable area.

            Privacy.
            We care about the privacy of our Users. You understand that by using the Sites you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in our Privacy Policy [link], and to have your personally identifiable information collected, used, transferred to and processed in the United States.

            Security.
            Compoundexuses commercially reasonable physical, managerial, and technical safeguards to preserve the integrity and security of your personal information and implement your privacy settings. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.

            Third-Party Links and Information.
            The Site may contain links to third-party materials that are not owned or controlled by Compound. Compoundex does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. If you access a third-party website or service from the Site on or through any third-party website or service, you do so at your own risk, and you understand that this Agreement and Compound’s Privacy Policy do not apply to your use of such sites. You expressly relieve Compoundex from any and all liability arising from your use of any third-party website, service, or content. Additionally, your dealings with or participation in promotions of advertisers found on the Site, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that Compoundex shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.

            Indemnity.
            You agree to defend, indemnify and hold harmless Compoundex and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Site, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) any content that you submit to the Site including without limitation misleading, false, or inaccurate information; (vi) your willful misconduct; or (vii) any other party’s access and use of the Site with your unique username, password or other appropriate security code if asked for.

            Assumption of Risk; Release of Claims.

            You acknowledge that the Site (including without limitation the Protocol and the Smart Contracts) and your use of the Site contain certain risks, including without limitation the following risks:

            That any Smart Contracts you interact with are entirely your own responsibility / liability, and Compoundex is not a party to the Smart Contracts; At any time, your access to your Assets may be suspended or terminated or there may be a delay in your access or use of your Assets which may result in the Assets diminishing in value or you being unable to complete a Smart Contract;if you are a borrower of Assets and if your collateral declines such that your collateral is no longer sufficient to secure your borrowed Assets, other Users may seize your collateral to close out your borrowed Asset balance; andThe Protocol may be suspended or terminated for any or no reason, which may limit your access to your Assets.
            Accordingly, you expressly agree that: (A) you assume all risk in connection with your access and use of the Site, the Protocol and the Smart Contracts; and (B) that you expressly waive and release Compoundex from any and all liability, claims, causes of action, or damages arising from or in any way related to your use of the Site, the Protocol or the Smart Contracts. If you are a California resident, you waive California Civil Code §1542, which says:

            “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”
            No Warranty.
            The Site is provided on an “as is” and “as available” basis. Use of the Site is at your own risk. To the maximum extent permitted by applicable law, the Site is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement. No advice or information, whether oral or written, obtained by you from Compoundexor through the Site will create any warranty not expressly stated herein. Without limiting the foregoing, Compound, its subsidiaries, its affiliates, and its licensors do not warrant that the content is accurate, reliable or correct; that the Site will meet your requirements; that the Site will be available at any particular time or location, uninterrupted or secure; that any defects or errors will be corrected; or that the Site is free of viruses or other harmful components. Any content downloaded or otherwise obtained through the use of the Site is downloaded at your own risk and you will be solely responsible for any damage to your computer system or mobile device or loss of data that results from such download or your use of the Site.

            Compoundex does not warrant, endorse, guarantee, or assume responsibility for any product or site advertised or offered by a third party through the Site or any hyperlinked website or site, and Compoundex will not be a party to or in any way monitor any transaction between you and third-party providers of products or services.Limitation of Liability.

            To the maximum extent permitted by applicable law, in no event shall Compound, its affiliates, agents, directors, employees, suppliers or licensors be liable for any indirect, punitive, incidental, special, consequential or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data or other intangible losses, arising out of or relating to the use of, or inability to use, this Site. Under no circumstances will Compoundex be responsible for any damage, loss or injury resulting from hacking, tampering or other unauthorized access or use of the Site or the information contained therein.To the maximum extent permitted by applicable law, Compoundex  assumes no liability or responsibility for any (i) errors, mistakes, or inaccuracies of content; (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to or use of our site; (iii) any unauthorized access to or use of our secure servers and/or any and all personal information stored therein; (iv) any interruption or cessation of transmission to or from the Site; (v) any bugs, viruses, trojan horses, or the like that may be transmitted to or through our site by any third party; (vi) any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available through the Site; and/or (vii) User Content or the defamatory, offensive, or illegal conduct of any third party. In no event shall Compound, its affiliates, agents, directors, employees, suppliers, or licensors be liable to you for any claims, proceedings, liabilities, obligations, damages, losses or costs in an amount exceeding the amount you paid to Compoundex hereunder or $100.00USD, whichever is greater.

            This limitation of liability section applies whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, even if Compoundex has been advised of the possibility of such damage. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction.

            Limitations as Allowed by Law.
            Federal law, some states, provinces and other jurisdictions do not allow the exclusion and limitations of certain implied warranties, or the exclusion or limitation of incidental or consequential damages, so the above limitations or exclusions may not apply to you. This agreement gives you specific legal rights, and you may also have other rights which vary from state to state. The disclaimers, exclusions, and limitations of liability under this agreement will not apply to the extent prohibited by applicable law.
        </p>
      </div>
    )
  }
}
